### ISSUE TITLE
TODO : Mod Center API 0.1.0

### ISSUE THREAD

**Issue by skyecodes** [Franckyi/Mod-Center-API#1]
- [x] Universal database connection
- [x] Custom Statements (prepared or not)
- [x] Automatic detection of MC Versions
- [x] Add getFilesFromProject using MC Versions
- [x] Add getFileFromName
- [x] Add getProjectFromFile
- [x] Update detection [working on it]
- [x] Add categories
- [x] Dependency manager
- [x] Curse parser
- [x] ...
